<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.1</TargetFramework>
		<AssemblyName>StudioEnhancementSuite</AssemblyName>
		<Description>Various </Description>
		<Version>1.4.0</Version>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<LangVersion>latest</LangVersion>
		<RestoreAdditionalProjectSources>
			https://api.nuget.org/v3/index.json;
			https://nuget.bepinex.dev/v3/index.json
		</RestoreAdditionalProjectSources>
		<RootNamespace>StudioEnhancementSuite</RootNamespace>
		<Nullable>enable</Nullable>
		<RunPostBuildEvent>OnOutputUpdated</RunPostBuildEvent>
	</PropertyGroup>

	<PropertyGroup>
		<StudioStable>C:\Program Files\Studio 2.0 EarlyAccess</StudioStable>
		<StudioEA>C:\Program Files\Studio 2.0 EarlyAccess</StudioEA>
		<StudioDlls>$(StudioEA)\Studio_Data\Managed</StudioDlls>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="BepInEx.Analyzers" Version="1.*" PrivateAssets="all" />
		<PackageReference Include="BepInEx.Core" Version="5.*" />
		<PackageReference Include="BepInEx.PluginInfoProps" Version="2.*" />
		<PackageReference Include="Krafs.Publicizer" Version="2.*" />
		<PackageReference Include="UnityEngine.Modules" Version="2022.3.20" IncludeAssets="compile" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework.TrimEnd(`0123456789`))' == 'net'">
		<PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.2" PrivateAssets="all" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="..\lib\" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="Studio">
			<HintPath>$(StudioDlls)\Studio.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="Studio.Common">
			<HintPath>$(StudioDlls)\BrickLink.Studio.Common.Runtime.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="Studio.Application">
			<HintPath>$(StudioDlls)\Studio.Application.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="Studio.Presentation">
			<HintPath>$(StudioDlls)\Studio.Presentation.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="Studio.DataModel">
			<HintPath>$(StudioDllDir)\Studio.DataModel.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="Zenject">
			<HintPath>$(StudioDlls)\Zenject.dll</HintPath>
			<Private>False</Private>
		</Reference>
	</ItemGroup>

	<ItemGroup>
		<Publicize Include="Studio" />
	</ItemGroup>


	<Target Name="PostBuild" AfterTargets="PostBuildEvent" Condition="Exists($(GameDir))">
		<Copy SourceFiles="$(TargetPath)" DestinationFolder="$(GameDir)\BepInEx\plugins" />
	</Target>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Copy SourceFiles="$(TargetPath)" DestinationFolder="$(StudioStable)\BepInEx\plugins" />
		<Copy SourceFiles="$(TargetPath)" DestinationFolder="$(StudioEA)\BepInEx\plugins" />
	</Target>
</Project>
